name: edk2 build
on: [push,workflow_dispatch]

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubicloud-standard-2
            platform: x64
            edk2_version: edk2-stable202311
            edk2_commit: 8736b8fdca85e02933cdb0a13309de14c9799ece

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install uuid-dev iasl build-essential python3-distutils git libbrotli-dev nasm
      - name: Build edk2
        run: EDK2_COMMIT=${{ matrix.edk2_commit}} ./build-edk2
      - name: List produced files
        run: ls
      - uses: ncipollo/release-action@v1
        if: github.event_name == 'workflow_dispatch'
        with:
          artifacts: "${{ github.workspace }}/CLOUDHV-${{ matrix.platform }}.fd"
          body: "Release ${{ matrix.edk2_version }}-${{ matrix.platform }}"
          name: "${{ matrix.edk2_version }}-${{ matrix.platform }}"
          tag: "${{ matrix.edk2_version }}-${{ matrix.platform }}"
          allowUpdates: true
